{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'url': ''}\n"
     ]
    }
   ],
   "source": [
    "import requests\n",
    "\n",
    "r = requests.post(\n",
    "\t\"http://localhost:8080/predict\", \n",
    "\tjson={\"url\":\"\"}\n",
    ")\n",
    "\n",
    "print(r.json())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yes\n"
     ]
    }
   ],
   "source": [
    "\n",
    "r = requests.post(\n",
    "\t\"http://localhost:8080/download_registry_model\", \n",
    "\tjson={\"model_name\":\"log_reg_shot_dist_and_angle\",\"version\":\"pp\"}\n",
    ")\n",
    "\n",
    "print(r.json())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "INFO:app:{'qq': 'pp', 'qwdqwd': 123}\n",
      "ERROR:app:Exception on /predict [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1519, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1517, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1503, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\yujd1\\Documents\\GitHub\\datascience\\milestone3\\serving\\app.py\", line 112, in predict\n",
      "    raise NotImplementedError(\"TODO: implement this enpdoint\")\n",
      "NotImplementedError: TODO: implement this enpdoint\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:01:43] \"\u001b[35m\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" 500 -\n",
      "INFO:app:{'qq': 'pp'}\n",
      "ERROR:app:Exception on /predict [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1519, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1517, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1503, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\yujd1\\Documents\\GitHub\\datascience\\milestone3\\serving\\app.py\", line 112, in predict\n",
      "    raise NotImplementedError(\"TODO: implement this enpdoint\")\n",
      "NotImplementedError: TODO: implement this enpdoint\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:02:27] \"\u001b[35m\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" 500 -\n",
      "INFO:app:qq\n",
      "ERROR:app:Exception on /predict [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1519, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1517, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1503, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\yujd1\\Documents\\GitHub\\datascience\\milestone3\\serving\\app.py\", line 112, in predict\n",
      "    raise NotImplementedError(\"TODO: implement this enpdoint\")\n",
      "NotImplementedError: TODO: implement this enpdoint\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:02:39] \"\u001b[35m\u001b[1mPOST /predict HTTP/1.1\u001b[0m\" 500 -\n",
      "INFO:app:qq\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:03:02] \"POST /predict HTTP/1.1\" 200 -\n",
      "INFO:app:{'qq': 'pp', 'qwdqwd': 123}\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:03:10] \"POST /predict HTTP/1.1\" 200 -\n",
      "INFO:app:{'url': ''}\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:04:03] \"POST /predict HTTP/1.1\" 200 -\n",
      "INFO:app:{'url': ''}\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:04:09] \"POST /predict HTTP/1.1\" 200 -\n",
      "INFO:app:{'url': ''}\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:04:15] \"POST /predict HTTP/1.1\" 200 -\n",
      "ERROR:app:Exception on /logs [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1519, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1517, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1503, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\yujd1\\Documents\\GitHub\\datascience\\milestone3\\serving\\app.py\", line 53, in logs\n",
      "    raise NotImplementedError(\"TODO: implement this endpoint\")\n",
      "NotImplementedError: TODO: implement this endpoint\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:07:12] \"\u001b[35m\u001b[1mGET /logs HTTP/1.1\u001b[0m\" 500 -\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:07:35] \"GET /logs HTTP/1.1\" 200 -\n",
      "ERROR:app:Exception on /logs [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1519, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1517, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1503, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\yujd1\\Documents\\GitHub\\datascience\\milestone3\\serving\\app.py\", line 63, in logs\n",
      "    return jsonify(response)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 302, in jsonify\n",
      "    f\"{dumps(data, indent=indent, separators=separators)}\\n\",\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 132, in dumps\n",
      "    return _json.dumps(obj, **kwargs)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\__init__.py\", line 238, in dumps\n",
      "    **kw).encode(obj)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 51, in default\n",
      "    return super().default(o)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type bytes is not JSON serializable\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:15:49] \"\u001b[35m\u001b[1mGET /logs HTTP/1.1\u001b[0m\" 500 -\n",
      "ERROR:app:Exception on /logs [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1519, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1517, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1503, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\yujd1\\Documents\\GitHub\\datascience\\milestone3\\serving\\app.py\", line 63, in logs\n",
      "    return jsonify(response)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 302, in jsonify\n",
      "    f\"{dumps(data, indent=indent, separators=separators)}\\n\",\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 132, in dumps\n",
      "    return _json.dumps(obj, **kwargs)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\__init__.py\", line 238, in dumps\n",
      "    **kw).encode(obj)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 51, in default\n",
      "    return super().default(o)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type bytes is not JSON serializable\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:16:31] \"\u001b[35m\u001b[1mGET /logs HTTP/1.1\u001b[0m\" 500 -\n",
      "ERROR:app:Exception on /logs [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1519, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1517, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1503, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\yujd1\\Documents\\GitHub\\datascience\\milestone3\\serving\\app.py\", line 63, in logs\n",
      "    return jsonify(response)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 302, in jsonify\n",
      "    f\"{dumps(data, indent=indent, separators=separators)}\\n\",\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 132, in dumps\n",
      "    return _json.dumps(obj, **kwargs)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\__init__.py\", line 238, in dumps\n",
      "    **kw).encode(obj)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 51, in default\n",
      "    return super().default(o)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type bytes is not JSON serializable\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:16:39] \"\u001b[35m\u001b[1mGET /logs HTTP/1.1\u001b[0m\" 500 -\n",
      "ERROR:app:Exception on /logs [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1519, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1517, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1503, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\yujd1\\Documents\\GitHub\\datascience\\milestone3\\serving\\app.py\", line 63, in logs\n",
      "    return jsonify(response)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 302, in jsonify\n",
      "    f\"{dumps(data, indent=indent, separators=separators)}\\n\",\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 132, in dumps\n",
      "    return _json.dumps(obj, **kwargs)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\__init__.py\", line 238, in dumps\n",
      "    **kw).encode(obj)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 51, in default\n",
      "    return super().default(o)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type bytes is not JSON serializable\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:17:27] \"\u001b[35m\u001b[1mGET /logs HTTP/1.1\u001b[0m\" 500 -\n",
      "ERROR:app:Exception on /logs [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1519, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1517, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1503, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\yujd1\\Documents\\GitHub\\datascience\\milestone3\\serving\\app.py\", line 63, in logs\n",
      "    return jsonify(response)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 302, in jsonify\n",
      "    f\"{dumps(data, indent=indent, separators=separators)}\\n\",\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 132, in dumps\n",
      "    return _json.dumps(obj, **kwargs)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\__init__.py\", line 238, in dumps\n",
      "    **kw).encode(obj)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 51, in default\n",
      "    return super().default(o)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type bytes is not JSON serializable\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:19:26] \"\u001b[35m\u001b[1mGET /logs HTTP/1.1\u001b[0m\" 500 -\n",
      "ERROR:app:Exception on /logs [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1519, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1517, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1503, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\yujd1\\Documents\\GitHub\\datascience\\milestone3\\serving\\app.py\", line 63, in logs\n",
      "    return jsonify(response)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 302, in jsonify\n",
      "    f\"{dumps(data, indent=indent, separators=separators)}\\n\",\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 132, in dumps\n",
      "    return _json.dumps(obj, **kwargs)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\__init__.py\", line 238, in dumps\n",
      "    **kw).encode(obj)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 51, in default\n",
      "    return super().default(o)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type bytes is not JSON serializable\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:19:59] \"\u001b[35m\u001b[1mGET /logs HTTP/1.1\u001b[0m\" 500 -\n",
      "ERROR:app:Exception on /logs [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1519, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1517, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1503, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\yujd1\\Documents\\GitHub\\datascience\\milestone3\\serving\\app.py\", line 63, in logs\n",
      "    return jsonify(response)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 302, in jsonify\n",
      "    f\"{dumps(data, indent=indent, separators=separators)}\\n\",\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 132, in dumps\n",
      "    return _json.dumps(obj, **kwargs)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\__init__.py\", line 238, in dumps\n",
      "    **kw).encode(obj)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 51, in default\n",
      "    return super().default(o)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type bytes is not JSON serializable\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:20:55] \"\u001b[35m\u001b[1mGET /logs HTTP/1.1\u001b[0m\" 500 -\n",
      "ERROR:app:Exception on /logs [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1519, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1517, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1503, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\yujd1\\Documents\\GitHub\\datascience\\milestone3\\serving\\app.py\", line 63, in logs\n",
      "    return jsonify(response)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 302, in jsonify\n",
      "    f\"{dumps(data, indent=indent, separators=separators)}\\n\",\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 132, in dumps\n",
      "    return _json.dumps(obj, **kwargs)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\__init__.py\", line 238, in dumps\n",
      "    **kw).encode(obj)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 51, in default\n",
      "    return super().default(o)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type bytes is not JSON serializable\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:21:05] \"\u001b[35m\u001b[1mGET /logs HTTP/1.1\u001b[0m\" 500 -\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:22:28] \"GET /logs HTTP/1.1\" 200 -\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:22:34] \"GET /logs HTTP/1.1\" 200 -\n",
      "INFO:app:{'url': ''}\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:22:40] \"POST /predict HTTP/1.1\" 200 -\n",
      "ERROR:app:Exception on /logs [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1519, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1517, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1503, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\yujd1\\Documents\\GitHub\\datascience\\milestone3\\serving\\app.py\", line 63, in logs\n",
      "    return jsonify(response)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 302, in jsonify\n",
      "    f\"{dumps(data, indent=indent, separators=separators)}\\n\",\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 132, in dumps\n",
      "    return _json.dumps(obj, **kwargs)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\__init__.py\", line 238, in dumps\n",
      "    **kw).encode(obj)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 51, in default\n",
      "    return super().default(o)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type bytes is not JSON serializable\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:22:56] \"\u001b[35m\u001b[1mGET /logs HTTP/1.1\u001b[0m\" 500 -\n",
      "ERROR:app:Exception on /logs [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1519, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1517, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1503, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\yujd1\\Documents\\GitHub\\datascience\\milestone3\\serving\\app.py\", line 63, in logs\n",
      "    return jsonify(response)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 302, in jsonify\n",
      "    f\"{dumps(data, indent=indent, separators=separators)}\\n\",\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 132, in dumps\n",
      "    return _json.dumps(obj, **kwargs)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\__init__.py\", line 238, in dumps\n",
      "    **kw).encode(obj)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 51, in default\n",
      "    return super().default(o)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type bytes is not JSON serializable\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:23:39] \"\u001b[35m\u001b[1mGET /logs HTTP/1.1\u001b[0m\" 500 -\n",
      "ERROR:app:Exception on /logs [GET]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1519, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1517, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1503, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\yujd1\\Documents\\GitHub\\datascience\\milestone3\\serving\\app.py\", line 63, in logs\n",
      "    return jsonify(response)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 302, in jsonify\n",
      "    f\"{dumps(data, indent=indent, separators=separators)}\\n\",\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 132, in dumps\n",
      "    return _json.dumps(obj, **kwargs)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\__init__.py\", line 238, in dumps\n",
      "    **kw).encode(obj)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 199, in encode\n",
      "    chunks = self.iterencode(o, _one_shot=True)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 257, in iterencode\n",
      "    return _iterencode(o, 0)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\json\\__init__.py\", line 51, in default\n",
      "    return super().default(o)\n",
      "  File \"C:\\ProgramData\\miniconda3\\lib\\json\\encoder.py\", line 179, in default\n",
      "    raise TypeError(f'Object of type {o.__class__.__name__} '\n",
      "TypeError: Object of type bytes is not JSON serializable\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:23:57] \"\u001b[35m\u001b[1mGET /logs HTTP/1.1\u001b[0m\" 500 -\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:24:02] \"GET /logs HTTP/1.1\" 200 -\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:25:37] \"GET /logs HTTP/1.1\" 200 -\n",
      "INFO:app:logs read.\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:25:48] \"GET /logs HTTP/1.1\" 200 -\n",
      "INFO:app:{'url': ''}\n",
      "ERROR:app:Exception on /download_registry_model [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1519, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1517, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1503, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\yujd1\\Documents\\GitHub\\datascience\\milestone3\\serving\\app.py\", line 97, in download_registry_model\n",
      "    model_name = json[\"model_name\"]\n",
      "KeyError: 'model_name'\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:53:16] \"\u001b[35m\u001b[1mPOST /download_registry_model HTTP/1.1\u001b[0m\" 500 -\n",
      "INFO:app:{'url': ''}\n",
      "ERROR:app:Exception on /download_registry_model [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1519, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1517, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1503, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\yujd1\\Documents\\GitHub\\datascience\\milestone3\\serving\\app.py\", line 97, in download_registry_model\n",
      "    model_name = json[\"model_name\"]\n",
      "KeyError: 'model_name'\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:53:53] \"\u001b[35m\u001b[1mPOST /download_registry_model HTTP/1.1\u001b[0m\" 500 -\n",
      "INFO:app:{'url': 'ffff'}\n",
      "ERROR:app:Exception on /download_registry_model [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1519, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1517, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\yujd1\\AppData\\Roaming\\Python\\Python310\\site-packages\\flask\\app.py\", line 1503, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"C:\\Users\\yujd1\\Documents\\GitHub\\datascience\\milestone3\\serving\\app.py\", line 97, in download_registry_model\n",
      "    model_name = json[\"model_name\"]\n",
      "KeyError: 'model_name'\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:54:57] \"\u001b[35m\u001b[1mPOST /download_registry_model HTTP/1.1\u001b[0m\" 500 -\n",
      "INFO:app:logs read.\n",
      "INFO:werkzeug:127.0.0.1 - - [03/Dec/2023 23:55:24] \"GET /logs?model=qq&version=pp HTTP/1.1\" 200 -\n",
      "\n"
     ]
    }
   ],
   "source": [
    "r = requests.get(\n",
    "\t\"http://localhost:8080/logs\", \n",
    "    {\"model_name\":\"qq\",\"version\":\"pp\"}\n",
    ")\n",
    "\n",
    "print(r.json())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [],
   "source": [
    "from comet_ml import API"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [],
   "source": [
    "api = API(\"v5q8O8LftZtvOcoXlVM8Ku8fH\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [],
   "source": [
    "#get the Model object\n",
    "model = api.get_model(workspace=\"hfereidouni\", model_name=\"log_reg_shot_dist_and_angle\")\n",
    "\n",
    "model.download(\"1.9.0\",output_folder=\"./models/\", expand=True)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "metadata": {},
   "outputs": [],
   "source": [
    "json = {\"model_name\":1,\"version\":2,}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "metadata": {},
   "outputs": [],
   "source": [
    "api = API(\"v5q8O8LftZtvOcoXlVM8Ku8fH\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
